import { Pool } from 'pg';
import { getConfig } from '../config/env.js';

let pgPool: Pool | null = null;

/**
 * Inicializa y retorna el pool de conexiones de Postgres si DATABASE_URL está configurada.
 */
export async function getDbPool(): Promise<Pool> {
  if (pgPool) {
    return pgPool;
  }

  const config = getConfig();

  if (!config.DATABASE_URL) {
    throw new Error('DATABASE_URL is not configured. Direct database tools will not work.');
  }

  pgPool = new Pool({
    connectionString: config.DATABASE_URL,
    max: 10, // Maximum active connections for this MCP
    idleTimeoutMillis: 30000, // Close idle connections after 30s
    connectionTimeoutMillis: 5000, // Abort slow connection attempts
    statement_timeout: 10000, // (10s) Abort heavy/incorrect queries generated by the AI
  });

  try {
    // Verify connection with a simple query
    const client = await pgPool.connect();
    client.release();
    console.error(' Successfully connected to PostgreSQL (Pool with timeouts configured).');
    return pgPool;
  } catch (error: unknown) {
    pgPool = null;
    const msg = error instanceof Error ? error.message : String(error);
    console.error(' Error connecting to PostgreSQL:', msg);
    throw error;
  }
}

/**
 * Ejecuta una query segura usando el pool.
 */
export async function query(sql: string, params: unknown[] = []) {
  const pool = await getDbPool();
  try {
    const result = await pool.query(sql, params);
    return result.rows;
  } catch (error: unknown) {
    const msg = error instanceof Error ? error.message : String(error);
    console.error(' Error executing query:', msg);
    throw error;
  }
}
